SVM Classifier

Equation of the Hyperplane:

y = wx - b

Gradient Descent:

Gradient Descent is an optimization algorithm used for minimizing the loss function in various machine learning algorithms. It is used for updating the parameters of the learning model.

w = w - α*dw

b = b - α*db

Learning Rate:

Learning rate is a tuning parameter in an optimization algorithm that determines the step size at each iteration while moving toward a minimum of a loss function.

# Importing Dependencies

In [3]:
import numpy as np

# Support Vector Machine Classifer

In [4]:
class SVM_Classifier():

    # Initiating The Hyperparameters

    def __init__(self, learning_rate, no_of_iteration, lambda_parameter):

        self.learning_rate = learning_rate
        self.no_of_iteration = no_of_iteration
        self.lambda_parameter = lambda_parameter

    # Fitting the dataset to SVM Classifer

    def fit(self, X, Y):

        # m -> no of data points ( no of rows)
        # n -> no of input features (no of cols)

        self.m, n = X.shape

        # Initiating the weight value and bias value

        self.w = np.zeros(self.n)
        self.b = 0
        self.X = X
        self.Y = Y

        # Implementing Gradient Descent Algorithm for Optimization

        for i in range(self.no_of_iteration):
            self.update_weight()


    # Function for updating weight and bias value

    def update_weight(self):

        # Label Encoding
        y_label = np.where(self.Y <=0, -1, 1)


    # Gradients (dw,db)

        for index, x_i in enumerate(self.X):
            condition = y_label[index] * (np.dot(x_i, self.w) - self.b) >=1

            if (condition == True):

                dw = 2 * self.lambda_parameter * self.w
                db = 0

            else:

                dw = 2 * self.lambda_parameter * self.w - np.dot(x_i, y_label[index])
                db = y_label[index]


            self.w = self.w - self.learning_rate * dw
            self.b = self.b - self.learning_rate * db


    # Predict the label for the given input

    def predict(self, X):
        output = np.dot(X, self.w) - self.b

        predicted_labels = np.sign(output)

        y_hat = np.where(predicted_labels <=-1, 0, 1)

        return y_hat

# Importing Dependencies

In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Data Collection and Preprocessing

In [7]:
# Loading dataset

diabetes_data = pd.read_csv('diabetes.csv')

In [ ]:
# Print first five rows

diabetes_data.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [9]:
# Print last five rows

diabetes_data.tail()

     Pregnancies  Glucose  ...  Age  Outcome
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[5 rows x 9 columns]

In [10]:
# No of rows and cols

diabetes_data.shape

(768, 9)

In [12]:
# Statistical details

diabetes_data.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [13]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [14]:
# Checking null values

diabetes_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

- 0 --> Non-diabetic

- 1 --> Diabetic